version: "3.9"

volumes:
  mysql_data:
  backend_node_modules:
  frontend_node_modules:

services:
  # ---------------- MYSQL ----------------
  mysql:
    image: mysql:8
    container_name: booking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booking
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------- BACKEND ----------------
  backend:
    build:
      context: ./booking-backend
      dockerfile: Dockerfile.dev
    container_name: booking-backend
    ports:
      - "4000:4000"
    env_file:
      - ./booking-backend/.env
    volumes:
      - ./booking-backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  # ---------------- FRONTEND ----------------
  frontend:
    build:
      context: ./booking-frontend
      dockerfile: Dockerfile.dev
    container_name: booking-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./booking-frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - backend