# Dockerfile.dev
FROM node:20

WORKDIR /app

# Copiar package.json y package-lock.json / yarn.lock
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto del Vite dev server
EXPOSE 5173

# Comando por defecto
CMD ["npm", "run", "dev"]